'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('node:path');
const fs = require('node:fs');
const onchain = require('../src/launch/onchain');
const base58 = require('../src/launch/base58');

// Generated by onchain/tests/tests/vectors.rs from the Rust program crate.
const V = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'onchain-vectors.json'), 'utf8'));

test('addresses match the Rust program', () => {
  assert.strictEqual(onchain.idSeed('bp-001').toString('hex'), V.idSeed);
  assert.strictEqual(onchain.launchAddress(V.program, V.creator, 'bp-001'), V.launch);
  assert.strictEqual(onchain.vaultAddress(V.program, V.launch), V.vault);
  assert.strictEqual(onchain.escrowAddress(V.program, V.launch, V.investor), V.escrow);
  assert.strictEqual(onchain.associatedTokenAddress(V.vault, V.mint), V.vaultAta);
  assert.strictEqual(onchain.bondingCurveAddress(V.mint), V.bondingCurve);
});

test('init_launch encoding matches the Rust program', () => {
  const data = onchain.encodeInitLaunch({
    idSeed: onchain.idSeed('bp-001'),
    manifestHash: Buffer.alloc(32, 0xab),
    mint: V.mint,
    tokenProgram: onchain.TOKEN_2022_PROGRAM,
    buyback: V.buyback,
    feeBps: 1000,
    maxSlippageBps: 500,
    launchAt: 1_800_000_000,
    refundAfter: 1_800_003_600,
    commitments: [{ investor: V.investor, lamports: 1_500_000_000n }, { investor: V.creator, lamports: 100_000_000n }],
  });
  assert.strictEqual(data.toString('hex'), V.initData);
});

test('launch accounts decode', () => {
  const l = onchain.decodeLaunch(Buffer.from(V.launchAccount, 'hex'));
  assert.strictEqual(l.state, 'bought');
  assert.strictEqual(l.creator, V.creator);
  assert.strictEqual(l.feeBps, 1000);
  assert.strictEqual(l.launchAt, 1_800_000_000);
  assert.strictEqual(l.tokensBought, 42n);
  assert.deepStrictEqual(l.commitments.map((c) => [c.investor, c.lamports, c.funded]), [[V.investor, 1_500_000_000n, true], [V.creator, 100_000_000n, false]]);
});

test('SOL converts to lamports exactly', () => {
  assert.strictEqual(onchain.solToLamports(0.1), 100_000_000n);
  assert.strictEqual(onchain.solToLamports('1.5'), 1_500_000_000n);
  assert.strictEqual(onchain.solToLamports(2), 2_000_000_000n);
  assert.throws(() => onchain.solToLamports('0.0000000001'));
  assert.throws(() => onchain.solToLamports(-1));
});

test('on-curve check agrees with real keys and known PDAs', () => {
  const { publicKey } = require('node:crypto').generateKeyPairSync('ed25519');
  const raw = Buffer.from(publicKey.export({ format: 'jwk' }).x, 'base64url');
  assert.ok(onchain.isOnCurve(raw), 'a real ed25519 public key is on the curve');
  for (const pda of [V.launch, V.vault, V.escrow, V.vaultAta, V.bondingCurve]) assert.ok(!onchain.isOnCurve(base58.decode(pda)));
});

test('executeBuy refuses pump accounts that would buy for someone else', () => {
  const pumpKeys = Array.from({ length: 27 }, (_, i) => base58.encode(Buffer.alloc(32, i + 10)));
  const args = { payer: V.creator, launch: V.launch, mint: V.mint, buyback: V.buyback, pumpKeys, escrows: [V.escrow] };
  assert.throws(() => onchain.executeBuy(V.program, args), /vault/);
  pumpKeys[13] = V.vault;
  pumpKeys[14] = V.vaultAta;
  const ix = onchain.executeBuy(V.program, args);
  assert.strictEqual(ix.keys.length, 9 + 27 + 1);
  assert.ok(ix.keys[9 + 13].isWritable && !ix.keys[9 + 13].isSigner, 'vault signs inside the program, not in the transaction');
});
