'use strict';
// "My automation setup": per-user intake form -> full agent prompt + profile/product/.env files.
// Profiles live in localStorage. Keys stay in memory unless the user saves them encrypted.

const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const RAW = 'https://raw.githubusercontent.com/thegoodolbois/Bundlepad/main/';
const COMMON = ['TikTok', 'Instagram', 'YouTube', 'Facebook Pages', 'X (Twitter)', 'Threads', 'LinkedIn', 'Pinterest', 'Snapchat', 'Bluesky', 'Telegram', 'Discord'];
const ROUTE_NAMES = {
  official_api_own_account: 'Official API, my own account',
  user_sign_in_post_on_behalf: 'Sign in with the platform (OAuth app)',
  scheduler_or_automation_tool: 'Through a scheduler / hub',
  siri_shortcut: 'Siri Shortcut',
  native_scheduler: 'The platform’s own scheduler',
  manual: 'Manual (agent prepares, I post)',
};
const SEP = '|'; // path separator for data-bind (platform names contain dots)
const AGENT_MADE = /produced by|obtained by|generated by|returned by|from the agent|by the agent|agent'?s code exchange|agent-generated|the agent fetches/i;

let platforms = [], platformBy = {}, setupBy = {}, hubs = [];
let profiles = {}, current = '', secrets = {};

// ---- storage -------------------------------------------------------------------------
const store = {
  get(k, d) { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : d; } catch { return d; } },
  set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); return true; } catch { return false; } },
  del(k) { try { localStorage.removeItem(k); } catch { /* storage unavailable */ } },
};
function blankProfile() {
  return {
    user: { name: '', brand: '', what: '', url: '', link: '', goal: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || '', languages: 'English', countries: '', budget_tools: '', budget_ads: '', has: '' },
    products: [{ name: '', description: '', audience: '', price: '', url: '', facts: '', offer: '', mode: 'sell', aff_program: '', aff_pct: '', own_footage: '' }],
    platforms: {},
    hub: '',
    plan: { mix: '60% product, 30% helpful or entertaining, 10% behind the scenes', hashtags: '', avoid: '', ad_video_generator: '' },
    approval: { level: 'everything', channel: '', window: 'Review Mon-Tue, post Wed-Sun', approvers: '' },
    scripts: { voice: '', seconds: '30', sources: '', past: '' },
    video: { own_footage: '', voiceover: '', music: '', brand_kit: '', editor: '' },
    research: { enabled: 'yes', niches: '', keywords: '', mode: 'both', marketplaces: '', competitors: '', tools: '', landed_cost: '' },
    measure: { metrics: 'views, clicks, sales', tracking: '', report: 'Monday morning, by email' },
  };
}
const P = () => profiles[current];
let saveTimer = null;
function save() {
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    const ok = store.set('setup-profiles', profiles) && store.set('setup-current', current);
    $('#save-state').textContent = ok ? `Saved in this browser at ${new Date().toLocaleTimeString()}.` : 'This browser blocks storage: export profile.json to keep your answers.';
  }, 300);
}

// ---- path binding --------------------------------------------------------------------
function getPath(obj, path) { return path.split(SEP).reduce((o, k) => (o == null ? undefined : o[k]), obj); }
function setPath(obj, path, val) {
  const keys = path.split(SEP); let o = obj;
  keys.slice(0, -1).forEach((k) => { if (o[k] == null) o[k] = {}; o = o[k]; });
  o[keys[keys.length - 1]] = val;
}
const field = (path, label, opts = {}) => {
  const v = getPath(P(), path) ?? '';
  const ph = opts.ph ? ` placeholder="${esc(opts.ph)}"` : '';
  let input;
  if (opts.options) input = `<select data-bind="${esc(path)}">${opts.options.map(([k, n]) => `<option value="${esc(k)}" ${k === v ? 'selected' : ''}>${esc(n)}</option>`).join('')}</select>`;
  else if (opts.rows) input = `<textarea data-bind="${esc(path)}" rows="${opts.rows}"${ph}>${esc(v)}</textarea>`;
  else input = `<input data-bind="${esc(path)}" value="${esc(v)}"${ph}${opts.type ? ` type="${opts.type}"` : ''}>`;
  return `<label><span class="label">${esc(label)}</span>${input}</label>`;
};
const secretField = (name, hint, opts = {}) => {
  const env = envName(name);
  const sensitive = /high|critical/i.test(opts.sensitivity || '') || /TOKEN|SECRET|PASSWORD|KEY|WEBHOOK/i.test(env);
  const agentMade = opts.agentMade;
  return `<div class="secret-row"><label><span class="label">${esc(name)}${agentMade ? ' · your agent can get this for you' : ''}</span>
    <input data-secret="${esc(env)}" type="${sensitive ? 'password' : 'text'}" autocomplete="off" spellcheck="false" value="${esc(secrets[env] || '')}" placeholder="${agentMade ? 'Leave blank: the agent gets it when you sign in through it' : 'Paste here'}"></label>
    ${hint ? `<span class="note">Where: ${linkify(esc(hint))}</span>` : ''}</div>`;
};
const envName = (name) => String(name).split(/\s/)[0];
const linkify = (html) => html.replace(/https?:\/\/[^\s<>"')\]]+/g, (u) => `<a href="${u}" target="_blank" rel="noopener">${u}</a>`);
const lines = (t) => String(t || '').split(/\n/).map((x) => x.trim()).filter(Boolean);
const urlsIn = (arr) => [...new Set((arr || []).join(' ').match(/https?:\/\/[^\s<>"')\],]+/g) || [])].map((u) => u.replace(/[.,]$/, ''));

// ---- rendering -----------------------------------------------------------------------
function render() {
  const p = P();
  $('#app').innerHTML = `
  <section class="panel detail" id="s-you">
    <h2>1. You and your goals</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('user|name', 'Your name')}${field('user|brand', 'Brand or business name')}
      ${field('user|what', 'What you sell or make', { ph: 'desk lamps for students' })}${field('user|url', 'Website or store', { ph: 'https://' })}
      ${field('user|link', 'Main link posts should send people to', { ph: 'https://' })}${field('user|goal', 'Goal for the next 90 days', { ph: '100 sales/month, 10k followers…' })}
      ${field('user|timezone', 'Time zone')}${field('user|languages', 'Posting language(s)')}
      ${field('user|countries', 'Countries you sell to', { ph: 'US, UK' })}${field('user|has', 'Tools you already use', { ph: 'Buffer, Canva, iPhone, n8n…' })}
      ${field('user|budget_tools', 'Monthly budget for tools ($)', { type: 'number' })}${field('user|budget_ads', 'Monthly budget for paid ads ($)', { type: 'number' })}
    </div>
  </section>

  <section class="panel detail" id="s-products">
    <h2>2. Products and the facts you can prove</h2>
    <p class="note">Scripts may only say what is in "Facts". One fact per line, each one something you can show proof for.</p>
    ${p.products.map((x, i) => `<div class="pcard"><h3>Product ${i + 1}</h3>
      <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
        ${field(`products${SEP}${i}${SEP}name`, 'Name')}${field(`products${SEP}${i}${SEP}price`, 'Price')}
        ${field(`products${SEP}${i}${SEP}description`, 'What it is (one line)')}${field(`products${SEP}${i}${SEP}url`, 'Link to buy', { ph: 'https://' })}
        ${field(`products${SEP}${i}${SEP}audience`, 'Who it is for and their problem')}${field(`products${SEP}${i}${SEP}offer`, 'Offer / call to action', { ph: '15% off with code X, link in bio' })}
        ${field(`products${SEP}${i}${SEP}facts`, 'Facts you can prove (one per line)', { rows: 4 })}
        ${field(`products${SEP}${i}${SEP}own_footage`, 'Your own photos/videos of it (where?)', { rows: 4, ph: 'Google Drive folder, 8 clips' })}
        ${field(`products${SEP}${i}${SEP}mode`, 'You sell it or promote it?', { options: [['sell', 'I sell it'], ['affiliate', 'Affiliate (I promote it)']] })}
        ${field(`products${SEP}${i}${SEP}aff_program`, 'Affiliate program and commission %', { ph: 'Amazon Associates, 4%' })}
      </div>${p.products.length > 1 ? `<button class="btn" data-del-product="${i}" type="button">Remove product</button>` : ''}</div>`).join('')}
    <button class="btn" id="add-product" type="button">Add product</button>
  </section>

  <section class="panel detail" id="s-platforms">
    <h2>3. Platforms, sign-in and keys</h2>
    <p class="note">Pick your platforms. Each one shows the best way to automate it, the sign-in and developer pages to open, what you do, and the keys to paste. Leave a key blank if you want your agent to walk you through it.</p>
    <div class="filters" style="grid-template-columns:1fr"><label><span class="label">Find a platform</span><input id="pf-search" placeholder="Search 71 platforms"></label></div>
    <div class="chips" id="pf-chips"></div>
    <h3 style="margin-top:14px">Hub (one tool that posts to many platforms)</h3>
    <div class="filters" style="grid-template-columns:1fr">
      ${field('hub', 'Hub', { options: [['', 'No hub / decide later'], ...hubs.map((h) => [h.platform, h.platform])] })}
    </div>
    <div id="hub-card"></div>
    <div id="pf-cards"></div>
  </section>

  <section class="panel detail" id="s-plan">
    <h2>4. What to post and how often</h2>
    <p class="note">Posts per week and times are set per platform above. Ads use an AI-generated video from the script; daily and weekly posts use a compiled video from licensed footage.</p>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('plan|mix', 'Content mix')}${field('plan|ad_video_generator', 'AI video generator for ads', { ph: 'which tool, or none' })}
      ${field('plan|hashtags', 'Hashtags/keywords to use')}${field('plan|avoid', 'Words, topics, competitors to avoid')}
    </div>
  </section>

  <section class="panel detail" id="s-approval">
    <h2>5. Approval and notifications</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('approval|level', 'What needs your OK before posting?', { options: [['everything', 'Everything (recommended)'], ['scripts', 'Scripts only'], ['none-organic', 'Nothing for organic posts (ads still need OK)']] })}
      ${field('approval|channel', 'Send drafts to', { ph: 'Telegram, email, Discord, Slack, hub queue' })}
      ${field('approval|window', 'Review window')}${field('approval|approvers', 'Other approvers (optional)')}
    </div>
  </section>

  <section class="panel detail" id="s-scripts">
    <h2>6. Scripts</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('scripts|voice', 'Your voice and style', { ph: 'casual, first person, light humor' })}
      ${field('scripts|seconds', 'Video length', { options: [['15', '15 s'], ['30', '30 s'], ['60', '60 s']] })}
      ${field('scripts|sources', 'Scripts/videos you like (paste text or links; separate with ---)', { rows: 5 })}
      ${field('scripts|past', 'Scripts you already posted (so they never repeat; separate with ---)', { rows: 5 })}
    </div>
    ${secretField('ANTHROPIC_API_KEY', 'https://console.anthropic.com → API keys (needed for automatic script writing; without it the agent uses --prompt-only)', { sensitivity: 'high' })}
  </section>

  <section class="panel detail" id="s-video">
    <h2>7. Video and audio</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('video|own_footage', 'Your own footage (how many clips, where)')}${field('video|voiceover', 'Voiceover', { ph: 'my voice / AI voice (which service)' })}
      ${field('video|music', 'Music library (licensed for every platform you use?)')}${field('video|brand_kit', 'Brand kit: logo, colors, fonts, caption style')}
      ${field('video|editor', 'Editing tool you use, if any', { ph: 'CapCut, Canva, Descript, none' })}
    </div>
    ${secretField('PEXELS_API_KEY', 'https://www.pexels.com/api/ (free)')}
    ${secretField('PIXABAY_API_KEY', 'https://pixabay.com/api/docs/ (free, shown when logged in)')}
  </section>

  <section class="panel detail" id="s-research">
    <h2>8. Market research</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('research|enabled', 'Run weekly research?', { options: [['yes', 'Yes'], ['no', 'No']] })}
      ${field('research|mode', 'Sell, affiliate or both', { options: [['both', 'Both'], ['sell', 'Sell'], ['affiliate', 'Affiliate']] })}
      ${field('research|niches', 'Niches/categories to watch')}${field('research|keywords', 'Up to 10 keywords')}
      ${field('research|marketplaces', 'Where you sell', { ph: 'Shopify, Amazon, TikTok Shop, Etsy' })}${field('research|landed_cost', 'Supplier and landed cost per unit')}
      ${field('research|competitors', 'Competitors (links)', { rows: 3 })}${field('research|tools', 'Paid research tools you have', { rows: 3, ph: 'Kalodata, Keepa, none' })}
    </div>
  </section>

  <section class="panel detail" id="s-measure">
    <h2>9. Measuring results</h2>
    <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
      ${field('measure|metrics', 'Numbers that matter')}${field('measure|tracking', 'Where sales are tracked', { ph: 'Shopify analytics, UTM links, codes' })}
      ${field('measure|report', 'Weekly report: when and where')}
    </div>
  </section>

  <section class="panel detail" id="s-generate">
    <h2>10. Generate your agent prompt</h2>
    <p class="note">The prompt lists which keys you provided, by name only. Give your agent the keys separately: download the .env file and put it in your agent's secret store.</p>
    <p><button class="btn primary" id="gen" type="button">Generate prompt</button> <button class="btn" id="gen-copy" type="button">Copy prompt</button>
      <button class="btn" id="dl-prompt" type="button">Download prompt.txt</button> <button class="btn" id="dl-profile" type="button">Download profile.json</button>
      <button class="btn" id="dl-products" type="button">Download product.json files</button> <button class="btn" id="dl-env" type="button">Download .env (keys)</button></p>
    <div id="missing"></div>
    <pre class="prompt" id="prompt-out"></pre>
    <h3>Remember my keys on this device (optional)</h3>
    <p class="note">Keys are encrypted with your passphrase (AES-GCM) before they are saved in this browser. Without the passphrase they can't be read. Forget the passphrase and you re-enter the keys.</p>
    <div class="filters" style="grid-template-columns:2fr 1fr 1fr">
      <label><span class="label">Passphrase</span><input id="vault-pass" type="password" autocomplete="new-password"></label>
      <label><span class="label">&nbsp;</span><button class="btn" id="vault-save" type="button">Save keys encrypted</button></label>
      <label><span class="label">&nbsp;</span><button class="btn" id="vault-open" type="button">Unlock saved keys</button></label>
    </div>
    <p class="note" id="vault-state"></p>
  </section>`;
  drawChips();
  drawPlatformCards();
  drawHub();
  $('#vault-state').textContent = store.get('setup-vault:' + current, null) ? 'Encrypted keys are saved for this profile. Enter the passphrase and press Unlock.' : 'No saved keys for this profile.';
}

function drawChips() {
  const q = ($('#pf-search') && $('#pf-search').value || '').toLowerCase();
  const chosen = P().platforms;
  const list = platforms.filter((x) => !q || x.platform.toLowerCase().includes(q) || (x.category || '').toLowerCase().includes(q));
  $('#pf-chips').innerHTML = list.map((x) => `<label class="chip"><input type="checkbox" data-pf="${esc(x.platform)}" ${chosen[x.platform] ? 'checked' : ''}>${esc(x.platform)}${x.has_upload_api ? '' : ' · no API'}</label>`).join('');
}

function routeOptions(pf) {
  return (pf.automation_options || []).map((o) => [o.route, `${ROUTE_NAMES[o.route] || o.route}${o.cost ? ' · ' + o.cost : ''}`]);
}

function drawPlatformCards() {
  const chosen = P().platforms;
  $('#pf-cards').innerHTML = Object.keys(chosen).map((name) => {
    const pf = platformBy[name]; const st = setupBy[name] || {};
    if (!pf) return '';
    const c = chosen[name];
    if (!c.route) c.route = (pf.automation_options || [])[0] ? pf.automation_options[0].route : 'manual';
    const opt = (pf.automation_options || []).find((o) => o.route === c.route) || {};
    const steps = st.human_steps || [];
    const done = c.done || {};
    const links = urlsIn(steps).slice(0, 4);
    const base = `platforms${SEP}${name}${SEP}`;
    return `<div class="pcard" data-card="${esc(name)}">
      <h3>${esc(name)}</h3>
      <p class="note">${pf.has_upload_api ? 'Has a posting API' : 'No posting API'} · ${esc(pf.api_free || '')} ${pf.approval ? '· ' + esc(String(pf.approval).slice(0, 160)) : ''}</p>
      <div class="filters" style="grid-template-columns:repeat(2,minmax(0,1fr))">
        ${field(base + 'route', 'How to automate it', { options: routeOptions(pf) })}
        ${field(base + 'handle', 'Your account / handle')}
        ${field(base + 'account_type', 'Account type', { options: [['', 'Not sure'], ['personal', 'Personal'], ['creator', 'Creator'], ['business', 'Business']] })}
        ${field(base + 'content', 'What you will post here', { ph: pf.content_types || '' })}
        ${field(base + 'per_week', 'Posts per week', { type: 'number' })}
        ${field(base + 'times', 'Posting times', { ph: '18:00, 21:00' })}
      </div>
      ${opt.summary ? `<p class="note"><b>Route:</b> ${esc(opt.summary)}${opt.access ? ' <b>Access:</b> ' + esc(opt.access) : ''}${opt.limits ? ' <b>Limits:</b> ' + esc(opt.limits) : ''}</p>` : ''}
      ${c.route === 'scheduler_or_automation_tool' && P().hub ? `<p class="note">Connect ${esc(name)} inside ${esc(P().hub)}; the hub key below covers it.</p>` : ''}
      ${links.length ? `<p><b>Sign in / set up:</b> ${links.map((u) => `<a class="btn" href="${esc(u)}" target="_blank" rel="noopener">${esc(new URL(u).hostname.replace(/^www\./, ''))}</a>`).join(' ')}</p>` : ''}
      ${steps.length ? `<details><summary>What you do (${Object.values(done).filter(Boolean).length}/${steps.length} done)</summary><ol>${steps.map((s, i) => `<li><label><input type="checkbox" data-step="${esc(name)}" data-i="${i}" ${done[i] ? 'checked' : ''}> ${linkify(esc(String(s).replace(/^\d+\.\s*/, '')))}</label></li>`).join('')}</ol></details>` : ''}
      ${(st.secrets_to_hand_over || []).filter((s) => c.route === 'scheduler_or_automation_tool' || !TOOL_SECRET.test(s.name + ' ' + (s.where_to_find || ''))).map((s) => secretField(s.name, s.where_to_find, { sensitivity: s.sensitivity, agentMade: AGENT_MADE.test(s.where_to_find || '') })).join('')}
      ${TESTS[name] ? `<p><button class="btn" data-test="${esc(name)}" type="button">Test my keys</button> <span class="note" data-test-out="${esc(name)}">${esc(c.test || '')}</span></p>` : ''}
    </div>`;
  }).join('') || '<p class="note">No platforms picked yet.</p>';
}

function drawHub() {
  const h = hubs.find((x) => x.platform === P().hub);
  $('#hub-card').innerHTML = h ? `<div class="pcard"><h3>${esc(h.platform)}</h3>
    ${urlsIn(h.human_steps).slice(0, 3).map((u) => `<a class="btn" href="${esc(u)}" target="_blank" rel="noopener">${esc(new URL(u).hostname.replace(/^www\./, ''))}</a>`).join(' ')}
    <details><summary>What you do (${(h.human_steps || []).length} steps)</summary><ol>${(h.human_steps || []).map((s) => `<li>${linkify(esc(String(s).replace(/^\d+\.\s*/, '')))}</li>`).join('')}</ol></details>
    ${(h.secrets_to_hand_over || []).map((s) => secretField(s.name, s.where_to_find, { sensitivity: s.sensitivity, agentMade: AGENT_MADE.test(s.where_to_find || '') })).join('')}</div>` : '';
}

// ---- key tests (browser calls the platform directly) ---------------------------------
const TESTS = {
  Telegram: async () => {
    const r = await fetch(`https://api.telegram.org/bot${need('TELEGRAM_BOT_TOKEN')}/getMe`).then((x) => x.json());
    if (!r.ok) throw new Error(r.description || 'token rejected');
    return `bot @${r.result.username} works`;
  },
  Bluesky: async () => {
    const pds = (secrets.BLUESKY_PDS || 'https://bsky.social').replace(/\/$/, '');
    const r = await fetch(`${pds}/xrpc/com.atproto.server.createSession`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identifier: need('BLUESKY_HANDLE'), password: need('BLUESKY_APP_PASSWORD') }) });
    const j = await r.json();
    if (!r.ok) throw new Error(j.message || r.status);
    return `signed in as ${j.handle}`;
  },
  'Mastodon / Fediverse': async () => {
    const r = await fetch(`${need('MASTODON_INSTANCE_URL').replace(/\/$/, '')}/api/v1/accounts/verify_credentials`, { headers: { Authorization: `Bearer ${need('MASTODON_ACCESS_TOKEN')}` } });
    const j = await r.json();
    if (!r.ok) throw new Error(j.error || r.status);
    return `token works for @${j.acct}`;
  },
  Discord: async () => {
    const r = await fetch(need('DISCORD_WEBHOOK_URL'));
    const j = await r.json();
    if (!r.ok) throw new Error(j.message || r.status);
    return `webhook "${j.name}" works`;
  },
};
function need(name) { if (!secrets[name]) throw new Error(`fill in ${name} first`); return secrets[name]; }

// ---- prompt generation ---------------------------------------------------------------
// Secrets that belong to a scheduler/hub rather than the platform's own API.
const TOOL_SECRET = /tool route|postiz|buffer|ayrshare|upload-post|zernio|outstand|publer|metricool|zapier|n8n|make\.com|ifttt/i;
function secretStatus(list, route) {
  return (list || []).filter((s) => !route || route === 'scheduler_or_automation_tool' || !TOOL_SECRET.test(s.name + ' ' + (s.where_to_find || ''))).map((s) => {
    const env = envName(s.name);
    const optional = /optional/i.test(s.name);
    const status = secrets[env] ? 'provided (in .env)' : AGENT_MADE.test(s.where_to_find || '') ? 'not provided: you can get it yourself during setup (see setup.json)' : optional ? 'not needed unless relevant' : 'MISSING: walk me through getting it';
    return { env, status, missing: status.startsWith('MISSING') };
  });
}

function collectMissing() {
  const p = P(); const m = [];
  if (!p.user.name && !p.user.brand) m.push('your name or brand (step 1)');
  if (!p.user.what) m.push('what you sell or make (step 1)');
  if (!p.user.link && !p.user.url) m.push('the link posts should send people to (step 1)');
  if (!p.user.goal) m.push('your 90-day goal (step 1)');
  p.products.forEach((x, i) => {
    if (!x.name) m.push(`product ${i + 1}: name (step 2)`);
    if (!lines(x.facts).length) m.push(`product ${i + 1}: facts you can prove (step 2)`);
    if (!x.offer) m.push(`product ${i + 1}: offer / call to action (step 2)`);
  });
  const names = Object.keys(p.platforms);
  if (!names.length) m.push('which platforms to post to (step 3)');
  names.forEach((n) => {
    const c = p.platforms[n];
    if (!c.handle) m.push(`${n}: your account handle (step 3)`);
    if (!c.per_week) m.push(`${n}: posts per week (step 3)`);
    const viaHub = c.route === 'scheduler_or_automation_tool';
    if (!viaHub) secretStatus((setupBy[n] || {}).secrets_to_hand_over, c.route).filter((s) => s.missing).forEach((s) => m.push(`${n}: ${s.env} (step 3)`));
  });
  if (names.some((n) => p.platforms[n].route === 'scheduler_or_automation_tool') && !p.hub) m.push('which hub/scheduler to use (step 3)');
  if (p.hub) secretStatus((hubs.find((h) => h.platform === p.hub) || {}).secrets_to_hand_over).filter((s) => s.missing).forEach((s) => m.push(`${p.hub}: ${s.env} (step 3)`));
  if (!p.approval.channel) m.push('where to send drafts for approval (step 5)');
  if (!p.scripts.voice) m.push('your voice and style (step 6)');
  if (!secrets.ANTHROPIC_API_KEY) m.push('ANTHROPIC_API_KEY, or confirm you want copy-paste prompts instead (step 6)');
  if (!p.video.own_footage) m.push('your own product footage (step 7)');
  if (!p.video.music) m.push('music library and its license (step 7)');
  return m;
}

function productJson(x) {
  return { name: x.name, description: x.description, audience: x.audience, facts: lines(x.facts), offer: x.offer, price: x.price, url: x.url, mode: x.mode, affiliate: x.mode === 'affiliate' ? x.aff_program : undefined, own_footage: x.own_footage || undefined };
}

function profileJson() {
  const p = P();
  return {
    generated: new Date().toISOString(),
    user: p.user,
    products: p.products.map(productJson),
    hub: p.hub,
    hub_secrets: p.hub ? Object.fromEntries(secretStatus((hubs.find((h) => h.platform === p.hub) || {}).secrets_to_hand_over).map((s) => [s.env, s.status])) : {},
    platforms: Object.entries(p.platforms).map(([n, c]) => ({
      platform: n, handle: c.handle, account_type: c.account_type, route: c.route, content: c.content, per_week: Number(c.per_week) || 0, times: c.times,
      human_steps_done: `${Object.values(c.done || {}).filter(Boolean).length}/${((setupBy[n] || {}).human_steps || []).length}`,
      secrets: Object.fromEntries(secretStatus((setupBy[n] || {}).secrets_to_hand_over, c.route).map((s) => [s.env, s.status])), test: c.test || 'not run',
    })),
    plan: p.plan, approval: p.approval,
    scripts: { ...p.scripts, sources: undefined, past: undefined, source_count: p.scripts.sources.split(/^\s*---\s*$/m).filter((t) => t.trim()).length, anthropic_key: secrets.ANTHROPIC_API_KEY ? 'provided' : 'missing' },
    video: { ...p.video, stock_keys: { PEXELS_API_KEY: secrets.PEXELS_API_KEY ? 'provided' : 'missing', PIXABAY_API_KEY: secrets.PIXABAY_API_KEY ? 'provided' : 'missing' } },
    research: p.research, measure: p.measure, unknowns: collectMissing(),
  };
}

function buildPrompt() {
  const p = P(); const prof = profileJson(); const missing = prof.unknowns;
  const who = p.user.brand || p.user.name || 'me';
  const out = [];
  out.push(`You are my content automation agent. Set up and run automated content for ${who}: market research, original scripts, videos, and scheduled posting to my own accounts.`);
  out.push(`READ FIRST
- Skills (how to use every part of the toolkit): ${RAW}marketing/data/skills.json. Start with "bundlepad", then follow "content-autopilot", which chains market-research, script-engine, video-sourcing and social-posting.
- Platform facts: ${RAW}marketing/data/platforms.json. Exact setup steps: ${RAW}marketing/data/setup.json (use each platform's human_steps, agent_steps and test_call; never guess).
- If you need anything not listed below, ask me using the intake steps in ${RAW}marketing/INTAKE.md.`);
  out.push(`RULES
- Secrets: I give you a .env file with the keys named below. Load them into your secret store. Never print, log or post them. Never ask for my passwords.
- Use only official APIs, webhooks, bots and tools built on them. No browser bots or scraping.
- Scripts may only use the facts listed per product. Every script must pass script-engine "check" as original. Never copy another creator's script or video.
- Approval: ${({ everything: 'show me every script and video before it is posted', scripts: 'show me every script before it is used; videos can go out without my OK', 'none-organic': 'organic posts can go out without my OK; ads and anything with a claim need my OK' })[p.approval.level]}. Send drafts to: ${p.approval.channel || '(ask me)'}. ${p.approval.window}${p.approval.approvers ? '. Other approvers: ' + p.approval.approvers : ''}.
- Add #ad / paid-partnership disclosure on affiliate or paid content and AI labels where a platform asks. Respect each platform's daily limits.`);
  out.push(`ABOUT ME
- Name / brand: ${[p.user.name, p.user.brand].filter(Boolean).join(' / ') || '(ask me)'}
- What I sell or make: ${p.user.what || '(ask me)'}
- Website: ${p.user.url || '-'} · Main link for posts: ${p.user.link || p.user.url || '(ask me)'}
- 90-day goal: ${p.user.goal || '(ask me)'}
- Time zone: ${p.user.timezone || '-'} · Languages: ${p.user.languages || '-'} · Countries: ${p.user.countries || '-'}
- Budget per month: tools $${p.user.budget_tools || '?'}, ads $${p.user.budget_ads || '?'}
- Tools I already use: ${p.user.has || '-'}`);
  out.push(`PRODUCTS (write each to its own product.json for script-engine)\n${prof.products.map((x) => JSON.stringify(x, null, 1)).join('\n')}`);
  const pfs = prof.platforms.map((c) => {
    const opt = ((platformBy[c.platform] || {}).automation_options || []).find((o) => o.route === c.route) || {};
    const viaHub = c.route === 'scheduler_or_automation_tool' && p.hub;
    return `### ${c.platform}
- Handle: ${c.handle || '(ask me)'} · account type: ${c.account_type || 'unknown'}
- Route: ${ROUTE_NAMES[c.route] || c.route}${viaHub ? ` through ${p.hub}` : ''}${opt.summary ? ` (${opt.summary})` : ''}
- Post: ${c.content || 'ask me'} · ${c.per_week || '?'} per week · times: ${c.times || 'pick good times for my audience'}${opt.limits ? `\n- Limits: ${opt.limits}` : ''}
- My setup progress: ${c.human_steps_done} of the human_steps done${viaHub ? '' : `\n- Keys: ${Object.entries(c.secrets).map(([k, v]) => `${k}: ${v}`).join('; ') || 'none needed'}`}
- Key test from the setup page: ${c.test}`;
  });
  out.push(`PLATFORMS\n${pfs.join('\n') || '(none picked yet: ask me which platforms)'}${p.hub ? `\n### Hub: ${p.hub}\n- Keys: ${Object.entries(prof.hub_secrets).map(([k, v]) => `${k}: ${v}`).join('; ')}` : ''}`);
  out.push(`CONTENT PLAN
- Mix: ${p.plan.mix}
- Ads: AI-generated video from the script${p.plan.ad_video_generator ? ` with ${p.plan.ad_video_generator}` : ' (ask me which generator)'}. Daily/weekly posts: compiled video from licensed footage (video-sourcing skill).
- Hashtags/keywords: ${p.plan.hashtags || '-'} · Avoid: ${p.plan.avoid || '-'}`);
  out.push(`SCRIPTS
- Voice: ${p.scripts.voice || '(ask me)'} · Length: ${p.scripts.seconds} s
- ANTHROPIC_API_KEY: ${secrets.ANTHROPIC_API_KEY ? 'provided (in .env)' : 'missing: use script-engine --prompt-only until I add it'}
- Scripts I like (add each with "script-engine add"; structure only, never copy):\n${p.scripts.sources.trim() ? p.scripts.sources.trim().split(/^\s*---\s*$/m).map((t, i) => `  [source ${i + 1}]\n  ${t.trim().replace(/\n/g, '\n  ')}`).join('\n') : '  (none yet: ask me for 3-10)'}
- Scripts I already posted (add each with "script-engine accept" so they never repeat):\n${p.scripts.past.trim() ? p.scripts.past.trim().split(/^\s*---\s*$/m).map((t, i) => `  [posted ${i + 1}]\n  ${t.trim().replace(/\n/g, '\n  ')}`).join('\n') : '  (none)'}`);
  out.push(`VIDEO AND AUDIO
- My footage: ${p.video.own_footage || '(ask me)'} · Voiceover: ${p.video.voiceover || '(ask me)'} · Music: ${p.video.music || '(ask me)'}
- Brand kit: ${p.video.brand_kit || '-'} · Editor: ${p.video.editor || '-'}
- Stock keys: PEXELS_API_KEY ${secrets.PEXELS_API_KEY ? 'provided' : 'missing'}, PIXABAY_API_KEY ${secrets.PIXABAY_API_KEY ? 'provided' : 'missing'}`);
  out.push(p.research.enabled === 'yes' ? `MARKET RESEARCH (weekly)
- Mode: ${p.research.mode} · Niches: ${p.research.niches || '-'} · Keywords: ${p.research.keywords || '-'}
- Where I sell: ${p.research.marketplaces || '-'} · Supplier / landed cost: ${p.research.landed_cost || '-'}
- Competitors: ${p.research.competitors || '-'} · Paid tools: ${p.research.tools || 'none'}` : 'MARKET RESEARCH: off for now.');
  out.push(`RESULTS
- Metrics: ${p.measure.metrics} · Sales tracking: ${p.measure.tracking || '(ask me)'} · Weekly report: ${p.measure.report}`);
  out.push(`STILL MISSING: ask me about these first\n${missing.length ? missing.map((x) => `- ${x}`).join('\n') : '- nothing'}`);
  out.push(`YOUR FIRST TASKS
1. Ask me about everything under STILL MISSING, a few questions at a time.
2. Load my .env into your secret store. For each key marked MISSING, walk me through that platform's human_steps one at a time.
3. Run every platform's test_call, then one private or test post each. Tell me what passed.
4. Write profile.json, the product.json files, and the posting schedule (hub queue, n8n, or cron).
5. Dry run: research, one script (recreate then check), one video, one test post. Show me the results.
6. Then start the content-autopilot weekly loop and send me the first weekly report.`);
  return out.join('\n\n');
}

// ---- files ---------------------------------------------------------------------------
function download(name, text, type = 'text/plain') {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([text], { type }));
  a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}
const slug = (s) => String(s || 'product').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'product';

// ---- encrypted key vault (WebCrypto) -------------------------------------------------
async function vaultKey(pass, salt) {
  const base = await crypto.subtle.importKey('raw', new TextEncoder().encode(pass), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey({ name: 'PBKDF2', salt, iterations: 250000, hash: 'SHA-256' }, base, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
}
const b64 = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf)));
const unb64 = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
async function vaultSave(pass) {
  const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await vaultKey(pass, salt), new TextEncoder().encode(JSON.stringify(secrets)));
  return store.set('setup-vault:' + current, { salt: b64(salt), iv: b64(iv), data: b64(data) });
}
async function vaultOpen(pass) {
  const v = store.get('setup-vault:' + current, null);
  if (!v) throw new Error('no saved keys for this profile');
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(v.iv) }, await vaultKey(pass, unb64(v.salt)), unb64(v.data));
  return JSON.parse(new TextDecoder().decode(plain));
}

// ---- profiles ------------------------------------------------------------------------
function drawProfiles() {
  $('#profile').innerHTML = Object.keys(profiles).map((n) => `<option ${n === current ? 'selected' : ''}>${esc(n)}</option>`).join('');
}
function switchProfile(name) { current = name; secrets = {}; drawProfiles(); render(); save(); }

// ---- events --------------------------------------------------------------------------
function wire() {
  const app = $('#app');
  app.addEventListener('input', (e) => {
    const t = e.target;
    if (t.dataset.bind) { setPath(P(), t.dataset.bind, t.value); save(); if (t.dataset.bind === 'hub') { drawHub(); drawPlatformCards(); } else if (/\|route$/.test(t.dataset.bind)) drawPlatformCards(); }
    if (t.dataset.secret) { secrets[t.dataset.secret] = t.value.trim(); $$(`[data-secret="${t.dataset.secret}"]`).forEach((x) => { if (x !== t) x.value = t.value; }); }
    if (t.id === 'pf-search') drawChips();
  });
  app.addEventListener('change', (e) => {
    const t = e.target;
    if (t.dataset.pf) {
      if (t.checked) P().platforms[t.dataset.pf] = P().platforms[t.dataset.pf] || { done: {} };
      else delete P().platforms[t.dataset.pf];
      save(); drawPlatformCards();
    }
    if (t.dataset.step) {
      const c = P().platforms[t.dataset.step]; c.done = c.done || {}; c.done[t.dataset.i] = t.checked; save();
      const sum = t.closest('details').querySelector('summary');
      sum.textContent = sum.textContent.replace(/\(\d+\//, `(${Object.values(c.done).filter(Boolean).length}/`);
    }
  });
  app.addEventListener('click', async (e) => {
    const t = e.target;
    if (t.id === 'add-product') { P().products.push(blankProfile().products[0]); save(); render(); }
    if (t.dataset.delProduct) { P().products.splice(Number(t.dataset.delProduct), 1); save(); render(); }
    if (t.dataset.test) {
      const name = t.dataset.test; const out = $(`[data-test-out="${CSS.escape(name)}"]`);
      out.textContent = 'Testing…';
      try { const msg = await TESTS[name](); P().platforms[name].test = `passed (${msg})`; out.innerHTML = `<span class="ok">Passed: ${esc(msg)}</span>`; }
      catch (err) { const msg = err instanceof TypeError ? 'the browser blocked the request; your agent will test it instead' : err.message; P().platforms[name].test = `failed (${msg})`; out.innerHTML = `<span class="bad">Failed: ${esc(msg)}</span>`; }
      save();
    }
    if (t.id === 'gen' || t.id === 'gen-copy' || t.id === 'dl-prompt') {
      const text = buildPrompt();
      $('#prompt-out').textContent = text;
      const m = collectMissing();
      $('#missing').innerHTML = m.length ? `<div class="callout"><span class="label">${m.length} item(s) still missing</span><br>Fill them in above, or leave them: the prompt tells your agent to ask you.</div>` : '<div class="callout"><span class="label">Complete</span><br>Nothing missing.</div>';
      if (t.id === 'gen-copy') { try { await navigator.clipboard.writeText(text); t.textContent = 'Copied'; } catch { t.textContent = 'Select the text to copy'; } }
      if (t.id === 'dl-prompt') download('agent-prompt.txt', text);
    }
    if (t.id === 'dl-profile') download('profile.json', JSON.stringify(profileJson(), null, 2), 'application/json');
    if (t.id === 'dl-products') P().products.forEach((x, i) => setTimeout(() => download(`product-${slug(x.name)}.json`, JSON.stringify(productJson(x), null, 2), 'application/json'), i * 300));
    if (t.id === 'dl-env') {
      const keys = Object.entries(secrets).filter(([, v]) => v);
      if (!keys.length) { alert('No keys entered yet.'); return; }
      if (!confirm('The .env file contains your keys in plain text. Give it only to your agent’s secret store, never post or share it. Download?')) return;
      download('.env', `# ${current}: keys for your content agent. Keep private.\n${keys.map(([k, v]) => `${k}=${JSON.stringify(v)}`).join('\n')}\n`);
    }
    if (t.id === 'vault-save') {
      const pass = $('#vault-pass').value;
      if (pass.length < 8) { $('#vault-state').textContent = 'Use a passphrase of at least 8 characters.'; return; }
      $('#vault-state').textContent = (await vaultSave(pass)) ? 'Keys saved, encrypted, in this browser.' : 'This browser blocks storage; keys were not saved.';
    }
    if (t.id === 'vault-open') {
      try { secrets = await vaultOpen($('#vault-pass').value); render(); $('#vault-state').textContent = 'Keys unlocked.'; }
      catch (err) { $('#vault-state').textContent = err.message === 'no saved keys for this profile' ? err.message : 'Wrong passphrase.'; }
    }
  });
  $('#profile').addEventListener('change', (e) => switchProfile(e.target.value));
  $('#p-new').addEventListener('click', () => {
    const name = (prompt('Name for the new profile (e.g. the person or brand):') || '').trim();
    if (!name) return;
    if (!profiles[name]) profiles[name] = blankProfile();
    switchProfile(name);
  });
  $('#p-del').addEventListener('click', () => {
    if (!confirm(`Delete the profile "${current}" and its saved keys from this browser?`)) return;
    delete profiles[current]; store.del('setup-vault:' + current);
    if (!Object.keys(profiles).length) profiles['My profile'] = blankProfile();
    switchProfile(Object.keys(profiles)[0]);
  });
  $('#p-import').addEventListener('click', () => $('#import-file').click());
  $('#import-file').addEventListener('change', async (e) => {
    const f = e.target.files[0]; if (!f) return;
    try {
      const j = JSON.parse(await f.text());
      const p = blankProfile();
      Object.assign(p.user, j.user || {});
      if (Array.isArray(j.products) && j.products.length) p.products = j.products.map((x) => ({ ...blankProfile().products[0], ...x, facts: Array.isArray(x.facts) ? x.facts.join('\n') : x.facts || '', aff_program: x.affiliate || '' }));
      for (const x of j.platforms || []) p.platforms[x.platform] = { handle: x.handle || '', account_type: x.account_type || '', route: x.route || '', content: x.content || '', per_week: x.per_week || '', times: x.times || '', done: {} };
      ['plan', 'approval', 'research', 'measure'].forEach((k) => Object.assign(p[k], j[k] || {}));
      Object.assign(p.video, j.video || {}); delete p.video.stock_keys;
      Object.assign(p.scripts, { voice: (j.scripts || {}).voice || '', seconds: String((j.scripts || {}).seconds || '30') });
      p.hub = j.hub || '';
      const name = (j.user && (j.user.brand || j.user.name)) || f.name.replace(/\.json$/, '');
      profiles[name] = p; switchProfile(name);
    } catch (err) { alert(`Couldn't read that file: ${err.message}`); }
    e.target.value = '';
  });
  $('#intake-copy').addEventListener('click', async (e) => {
    try { await navigator.clipboard.writeText($('#intake-text').textContent); e.target.textContent = 'Copied'; } catch { e.target.textContent = 'Select the text to copy'; }
  });
}

// Theme toggle (same as the guide page).
function applyTheme(t) { if (t) document.documentElement.dataset.theme = t; }
try { applyTheme(localStorage.getItem('theme')); } catch { /* storage unavailable */ }
$('#theme-btn').addEventListener('click', () => {
  const dark = document.documentElement.dataset.theme ? document.documentElement.dataset.theme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
  const next = dark ? 'light' : 'dark';
  applyTheme(next);
  try { localStorage.setItem('theme', next); } catch { /* storage unavailable */ }
});

(async () => {
  try {
    const [pj, sj, intake] = await Promise.all([
      fetch('data/platforms.json').then((r) => r.json()),
      fetch('data/setup.json').then((r) => r.json()),
      fetch('INTAKE.md').then((r) => r.text()).catch(() => ''),
    ]);
    platforms = pj.platforms.slice().sort((a, b) => ((COMMON.indexOf(a.platform) + 1 || 99) - (COMMON.indexOf(b.platform) + 1 || 99)) || (b.has_upload_api - a.has_upload_api) || a.platform.localeCompare(b.platform));
    platformBy = Object.fromEntries(platforms.map((x) => [x.platform, x]));
    setupBy = Object.fromEntries(sj.filter((s) => s.kind === 'platform').map((s) => [s.platform, s]));
    hubs = sj.filter((s) => s.kind === 'hub');
    const parts = intake.split(/\n---\n/);
    $('#intake-text').textContent = parts.length > 1 ? parts.slice(1).join('\n---\n').trim() : intake || 'Open INTAKE.md on GitHub.';
    profiles = store.get('setup-profiles', {}) || {};
    for (const k of Object.keys(profiles)) profiles[k] = { ...blankProfile(), ...profiles[k] };
    if (!Object.keys(profiles).length) profiles['My profile'] = blankProfile();
    current = store.get('setup-current', '') ;
    if (!profiles[current]) current = Object.keys(profiles)[0];
    drawProfiles(); render(); wire();
  } catch (err) {
    $('#app').innerHTML = `<p class="panel detail">Couldn't load the data (${esc(err.message)}). Open this page through GitHub Pages or a web server.</p>`;
  }
})();
